import Link from 'next/link';
import { ArrowRight, CalendarDays, MapPin } from 'lucide-react';
import { canPublicRegister, type PublicProgramBundle } from '../../lib/data/public-programs';

function dateLabel(date: string) { return new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric', year: 'numeric', timeZone: 'UTC' }).format(new Date(`${date}T00:00:00Z`)); }

export function DynamicPublicPrograms({ programs }: { programs: PublicProgramBundle[] }) {
  if (!programs.length) return <section className="demo-public-sessions shell"><div className="home-section-title"><div><p className="eyebrow">Programs</p><h2>New dates are coming</h2></div><p>Contact us to hear when the next program is scheduled.</p></div></section>;
  return <section className="demo-public-sessions shell" data-reveal><div className="home-section-title"><div><p className="eyebrow">Ongoing &amp; upcoming</p><h2>Programs for partner communities</h2></div><p>Each workshop is arranged for participants served by the named organization. Public registration appears only for Rookie Rackets-hosted camps.</p></div><div className="demo-public-session-list">{programs.map(({ program, sessions }) => { const publicRegistration = canPublicRegister(program, sessions); return <article className="demo-public-session" key={program.id}><div className="demo-public-session-copy"><span className={`status-badge status-${program.status}`}>{program.status.replaceAll('-', ' ')}</span><h3>{program.name}</h3><p>{program.description}</p><div className="demo-public-session-meta"><span><MapPin size={14} /> {program.venue}</span><span><CalendarDays size={14} /> {sessions.length ? sessions.map((session) => dateLabel(session.date)).join(' · ') : 'Dates coming soon'}</span></div>{!publicRegistration && program.type !== 'camp' && <p className="program-managed-note">Participation is reserved for this partner organization&apos;s group and managed directly by the partner.</p>}</div><div className="demo-public-session-actions">{publicRegistration && <Link className="button button-small" href={`/register/${program.slug}`}>{program.status === 'full' ? 'Join waitlist' : 'Register'}</Link>}<Link className="under-link" href={`/events/${program.slug}`}>View details <ArrowRight size={15} /></Link></div></article>; })}</div></section>;
}
