import Link from 'next/link';
import { SiteFooter, SiteHeader } from '../../components/site-shell';

const team = [['Adithya Burisetty','Founder & President'],['Aarav Gupta','VP Programs'],['Nikhil Peechara','VP Social Media'],['Nathan Kankanala','Senior Coach'],['Vihaan Darbha','Coach'],['Yuancheng Li','Coach'],['Ishan Kanchi','Coach'],['Tanay Kankanala','Coach']];

export default function About() { return <main className="about-page"><SiteHeader active="/about" />
  <section className="about-hero approved-split shell" data-reveal><div><h1>Built by high school students.<br/>Free for everyone.</h1><p>A student-led nonprofit making badminton accessible across NC.</p><div className="actions"><Link className="button button-blue" href="/events">View Events →</Link><Link className="plain-link" href="/contact">Sign Up</Link></div><em>Registered 501(c)(3)</em></div><img src="/images/story.webp" alt="Student coaches leading a Rookie Rackets workshop"/></section>
  <section className="about-story approved-split shell" data-reveal><div><h2>One student. One idea.<br/>A growing community.</h2><p>Rookie Rackets began in fall 2024, when a Green Hope High School student set out to make badminton more accessible. Today, eight student volunteers bring free coaching to communities across NC.</p><div className="fact-line"><span>EST. 2024</span><b>•</b><span>8 VOLUNTEERS</span><b>•</b><span>501(c)(3)</span></div><em>Badminton for every age, ability, and background.</em></div><img src="/images/coaching.webp" alt="A Rookie Rackets coach helping a beginner"/></section>
  <section className="about-coaching" data-reveal><div className="about-coaching-inner shell"><img src="/images/coaching.webp" alt="Patient beginner-first badminton instruction"/><div><h2>Competitive experience.<br/>Beginner-first teaching.</h2><p>National-level training meets patient, inclusive coaching.</p><div className="coach-stats"><span>Coach Hendry<br/>trained</span><span>6+ years<br/>coaching</span><span>$1,000+<br/>competition winnings</span></div><p>Free equipment, inclusive sessions, and a community where everyone belongs.</p></div></div></section>
  <section className="about-team shell" data-reveal><h2>Eight volunteers. One shared love for the sport.</h2><img src="/images/team.webp" alt="Rookie Rackets volunteers and workshop participants"/><div className="approved-team-list">{team.map(([name,role])=><div key={name}><span><strong>{name}</strong> — {role}</span><b>+</b></div>)}</div><Link className="text-link centered-link" href="/completed-events">Learn about our coaches →</Link></section>
  <section className="approved-cta" data-reveal><div className="shell"><div><h2>Ready to pick up a racket?</h2><p>Join the waitlist for upcoming sessions in Cary, NC.</p></div><Link className="button" href="/contact">Sign Up →</Link><Link href="/events">View Events</Link></div></section><SiteFooter />
</main>; }
