'use client';

import Link from 'next/link';
import { Building2, Filter, Search, X } from 'lucide-react';
import { useMemo, useState } from 'react';
import { formatDemoDate, getOwnerName } from '../../lib/demo/selectors';
import { useDemo } from '../demo/demo-provider';
import { EmptyState, StatusBadge } from '../demo/demo-ui';

export function OrganizationsView() {
  const { state } = useDemo();
  const [query, setQuery] = useState(''); const [type, setType] = useState('all'); const [stage, setStage] = useState('all'); const [owner, setOwner] = useState('all');
  const rows = useMemo(() => state.organizations.filter((organization) => organization.name.toLowerCase().includes(query.toLowerCase()) && (type === 'all' || organization.type === type) && (stage === 'all' || organization.status === stage) && (owner === 'all' || organization.leadStaffId === owner)), [owner, query, stage, state.organizations, type]);
  const clear = () => { setQuery(''); setType('all'); setStage('all'); setOwner('all'); };
  return <div className="staff-page"><div className="staff-page-heading"><div><p className="staff-kicker">Partnership desk</p><h1>Organizations</h1><p>Track the people and next steps behind each Rookie Rackets partnership.</p></div><div className="staff-summary-pill"><Building2 size={16} /> {state.organizations.length} partner records</div></div><div className="staff-filter-bar"><label><Search size={15} /><span className="sr-only">Search organizations</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search organizations" /></label><label><Filter size={14} /><span className="sr-only">Organization type</span><select value={type} onChange={(event) => setType(event.target.value)}><option value="all">All types</option>{Array.from(new Set(state.organizations.map((item) => item.type))).map((item) => <option key={item} value={item}>{item.replaceAll('-', ' ')}</option>)}</select></label><label><span className="sr-only">Stage</span><select value={stage} onChange={(event) => setStage(event.target.value)}><option value="all">All stages</option>{Array.from(new Set(state.organizations.map((item) => item.status))).map((item) => <option key={item} value={item}>{item.replaceAll('-', ' ')}</option>)}</select></label><label><span className="sr-only">Owner</span><select value={owner} onChange={(event) => setOwner(event.target.value)}><option value="all">All owners</option>{state.staffProfiles.map((profile) => <option value={profile.id} key={profile.id}>{profile.name}</option>)}</select></label>{(query || type !== 'all' || stage !== 'all' || owner !== 'all') && <button className="staff-clear" type="button" onClick={clear}><X size={14} /> Clear</button>}</div><div className="staff-record-table"><div className="staff-table-head"><span>Organization</span><span>Stage</span><span>Owner</span><span>Last update</span><span>Next step</span></div>{rows.length ? rows.map((organization) => <Link className="staff-table-row" href={`/staff/organizations/${organization.id}`} key={organization.id}><div className="table-primary"><span className="table-icon"><Building2 size={16} /></span><span><b>{organization.name}</b><small>{organization.type.replaceAll('-', ' ')} · {organization.address}</small></span></div><StatusBadge status={organization.status} /><span>{getOwnerName(state, organization.leadStaffId)}</span><span>{organization.lastUpdate}<small>{formatDemoDate(state.interactions.find((item) => item.organizationId === organization.id)?.date ?? state.demoDate)}</small></span><span className="next-step-cell">{organization.nextStep}</span></Link>) : <EmptyState title="No organizations match" description="Clear a filter to return to the partner list." action={<button className="staff-button staff-button-outline" type="button" onClick={clear}>Clear filters</button>} />}</div></div>;
}
