import Link from 'next/link';
import { DynamicPublicPrograms } from '../../components/public/dynamic-programs';
import { GalleryLightbox } from '../../components/site-interactions';
import { SiteFooter, SiteHeader } from '../../components/site-shell';

const photos=[{src:'/images/gallery-action-1.webp',alt:'Young players practicing over a badminton net',caption:'Learning at the net'},{src:'/images/story.webp',alt:'Coaches teaching a beginner group',caption:'Free instruction'},{src:'/images/gallery-outreach.webp',alt:'Rookie Rackets community outreach',caption:'Community outreach'},{src:'/images/gallery-certificates.webp',alt:'Players celebrating a completed workshop',caption:'Workshop celebrations'}];
const weeks=[['26','27','28','29','30','31','1'],['2','3','4','5','6','7','8'],['9','10','11','12','13','14','15'],['16','17','18','19','20','21','22'],['23','24','25','26','27','28','29'],['30','31','1','2','3','4','5']];

export default function Events(){return <main className="events-page"><SiteHeader active="/events" />
  <section className="events-hero shell" data-reveal><p className="eyebrow">NC Workshops</p><h1>Upcoming Events</h1><p>Free badminton workshops for all ages. No experience or equipment needed.</p><Link className="under-link" href="/contact">Get notified about new sessions →</Link></section>
  <section className="next-session shell" data-reveal><h2>Find your next session</h2><div className="session-grid"><div className="calendar"><div className="calendar-head"><span>‹</span><strong>August 2026</strong><span>›</span></div><div className="weekdays">{['SUN','MON','TUE','WED','THU','FRI','SAT'].map(d=><b key={d}>{d}</b>)}</div>{weeks.map((week,wi)=><div className="calendar-week" key={wi}>{week.map((day,di)=>{const muted=(wi===0&&di<6)||(wi===5&&di>1);const workshop=['7','14','21','28','4','5'].includes(day)&&(!muted||wi===5);return <span className={`${muted?'muted ':''}${workshop?'workshop ':''}${day==='28'?'next':''}`} key={`${wi}-${di}`}>{day}</span>})}</div>)}<p className="calendar-key"><i/> Workshop date</p></div><article className="next-card"><p className="eyebrow">Next up</p><h2><Link href="/events/boys-club-fall">Boys Club of Raleigh</Link></h2><h3>Fridays · Aug 28 – Sep 18, 2026</h3><dl><div><dt>Date</dt><dd>Fridays · Aug 28 – Sep 18, 2026</dd></div><div><dt>Time</dt><dd>4:00 – 5:00 PM</dd></div><div><dt>Location</dt><dd>Boys Club of Raleigh</dd></div></dl><p>An intro session for first-time players.<br/>Drop in and give badminton a try.</p><div className="session-perks"><span>Free</span><span>Equipment provided</span></div><Link className="button" href="/events/boys-club-fall">View details &amp; register →</Link></article></div></section>
  <section className="more-sessions shell" data-reveal><h2>More upcoming sessions</h2><div className="approved-schedule"><details><summary><strong><Link href="/events/tmsa-fall">TMSA Elementary Workshop</Link></strong><span>Oct 2, 9, 23 · Nov 6, 13, 2026</span><span>Time TBD</span><span>TMSA Elementary</span><em>Upcoming</em><b>+</b></summary><div className="event-record-detail"><p>Five free school workshops with registration open in this demo.</p><div className="event-record-actions"><Link className="button button-small" href="/register/tmsa-fall">Register for TMSA</Link><Link className="under-link" href="/events/tmsa-fall">View program details</Link><Link className="under-link" href="/sign-in?next=/portal/registrations">Open family account</Link></div></div></details><details><summary><strong><Link href="/events/carpenter-elementary">Carpenter Elementary Workshop</Link></strong><span>Date TBD</span><span>Time TBD</span><span>Carpenter Elementary</span><em>Dates coming soon</em><b>+</b></summary><div className="event-record-detail"><p>The next beginner workshop is in planning.</p><div className="event-record-actions"><Link className="under-link" href="/events/carpenter-elementary">View program details</Link><Link className="under-link" href="/sign-in?next=/portal/registrations">Open family account</Link></div></div></details></div><p>Join the waitlist and we’ll email you when registration opens.</p></section>
  <DynamicPublicPrograms />
  <section className="events-gallery shell" data-reveal><div className="home-section-title"><h2>From our sessions</h2><p>What happens when everyone shows up ready to play.</p></div><div className="event-approved-mosaic"><figure><img src={photos[0].src} alt={photos[0].alt}/><figcaption>{photos[0].caption}</figcaption></figure><div>{photos.slice(1,3).map(p=><figure key={p.src}><img src={p.src} alt={p.alt}/><figcaption>{p.caption}</figcaption></figure>)}</div></div><GalleryLightbox photos={photos}/></section>
  <section className="before-arrive" data-reveal><div className="shell"><h2>Before you arrive</h2><div><span><b>Duration</b>1–2 hours</span><span><b>Location</b>Cary, NC</span><span><b>Bring</b>Athletic shoes</span><span><b>We provide</b>Rackets and equipment</span></div><p>All ages and experience levels welcome. Beginners especially encouraged.</p></div></section>
  <section className="events-loop" data-reveal><div className="shell"><div><p className="eyebrow">Stay in the loop</p><h2>Be first to hear about new sessions.</h2><span>Free updates. No commitment.</span></div><div><Link className="button" href="/contact">Join the Waitlist →</Link><Link className="under-link" href="/faq">Read the FAQ</Link></div></div></section><SiteFooter />
</main>}
