import Link from 'next/link';
import { CountUp } from '../../components/motion';
import { SiteFooter, SiteHeader } from '../../components/site-shell';

export default function CompletedEvents(){return <main className="completed-page"><SiteHeader active="/completed-events" />
  <section className="completed-hero" data-reveal><div className="shell"><div><p className="eyebrow">Our journey</p><h1>Every session leaves a story behind.</h1><p>Workshops, camps, and community events since 2025.</p><div className="actions"><Link className="button" href="/contact">Join the Waitlist →</Link><Link className="under-link" href="/events">Upcoming Events</Link></div></div><img src="/images/hero-workshop.webp" alt="A Rookie Rackets coach leading a beginner workshop"/></div></section>
  <section className="completed-metrics shell" data-reveal><span><strong><CountUp end={60}/></strong> kids coached</span><b>•</b><span><strong><CountUp end={2}/></strong> workshops</span><b>•</b><span><strong><CountUp end={3}/></strong> camps</span><b>•</b><span><strong><CountUp end={1}/></strong> tournament</span><b>•</b><span><strong>$<CountUp end={5500}/></strong> raised</span></section>
  <section className="completed-story shell" data-reveal><img src="/images/hero-workshop.webp" alt="Carpenter Elementary workshop"/><div><p className="eyebrow">01 / Where it started</p><h2>Carpenter Elementary</h2><span>Sep–Oct 2025 · 10 first-time players</span><blockquote>“Ten beginners arrived without ever holding a racket.”</blockquote><p className="skill-line">Grip · Serve · Rally · Movement</p></div></section>
  <section className="completed-story reverse shell" data-reveal><div><p className="eyebrow">02 / A growing group</p><h2>TMSA Elementary</h2><span>Mar–Apr 2026 · 12 players · 5 weeks</span><blockquote>“Our most diverse group yet, learning across grade levels.”</blockquote><p className="skill-line">Overhead clears · Net play · Footwork</p></div><img src="/images/gallery-certificates.webp" alt="TMSA Elementary students with workshop certificates"/></section>
  <section className="completed-story shell" data-reveal><img src="/images/gallery-community.webp" alt="Community Smash event at Peak Sports"/><div><p className="eyebrow">03 / Funding the mission</p><h2>Community Smash</h2><span>Feb 21, 2026 · Peak Sports Morrisville · with ShuttleZone</span><p>Singles and doubles brought the community together—and helped keep every workshop free.</p><div className="smash-metrics"><span><strong><CountUp end={200}/></strong>participants</span><span><strong>$<CountUp end={4500}/>+</strong>raised</span></div></div></section>
  <section className="summer-record shell" data-reveal><h2>Summer 2026</h2><p>Three camps. Three partnerships. More time on court.</p><div><figure><img src="/images/gallery-outreach.webp" alt="Vibha partnership camp"/><figcaption><strong>Vibha Partnership</strong><span>One week of 3-hour sessions</span></figcaption></figure><figure><img src="/images/story.webp" alt="Rookie Rackets Camp 2"/><figcaption><strong>Rookie Rackets Camp 2</strong><span>Technique and game play</span></figcaption></figure><figure><img src="/images/outreach.webp" alt="RJourney summer camp"/><figcaption><strong>RJourney Camp</strong><span>Introducing more kids to badminton</span></figcaption></figure></div></section>
  <section className="full-record shell" data-reveal><h2>The full record</h2>{[['Sep–Oct 2025','Carpenter Elementary Workshop'],['Feb 21, 2026','Community Smash'],['Mar–Apr 2026','TMSA Elementary Workshop'],['Summer 2026','Vibha Partnership Camp'],['Summer 2026','Rookie Rackets Summer Camp 2'],['Summer 2026','RJourney Summer Camp']].map(([date,name])=><details key={name}><summary><span>{date}</span><strong>{name}</strong><b>+</b></summary><p>Free instruction, equipment, and a welcoming first experience with badminton.</p></details>)}</section>
  <section className="approved-cta" data-reveal><div className="shell"><div><h2>Be part of the next story.</h2><p>Join the waitlist for upcoming sessions.</p></div><Link className="button" href="/contact">Sign Up →</Link><Link href="/events">View Upcoming Events</Link></div></section><SiteFooter />
</main>}
